[build]
  publish = "."
  command = "echo No build step"

[[redirects]]
  from = "/representatives"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
