[build]
base = "/"
publish = "_site"

  command = """
    echo "Starting combined build..." && \
    # Create clean publish directory
    rm -rf _site && \
    mkdir -p _site && \
    # Build brahdb (Vite/React)
    echo "Building brahdb (Vite)..." && \
    (cd brahdb && npm install && npm run build) && \
    # Build decks (Eleventy)
    echo "Building decks (Eleventy)..." && \
    (cd decks && npm install && npm run build) && \
    # Copy static projects and root files
    echo "Copying static projects and root files..." && \
    cp -r index.html _site/ && \
    cp -r css _site/css && \
    cp -r bexarvoting _site/bexarvoting && \
    cp -r friendfinder _site/friendfinder && \
    # Copy built projects to their destinations
    echo "Copying built projects..." && \
    mkdir -p _site/brahdb && \
    cp -r brahdb/dist/* _site/brahdb/ && \
    cp -r brahdb/public/logos _site/brahdb/ && \
    cp -r brahdb/public/reviews _site/brahdb/ && \
    cp -r decks/_site _site/decks && \
    echo "Combined build finished successfully."
  """

# Specify Node.js version for modern features
[build.environment]
  NODE_VERSION = "20"

# Optional: Specify Node.js version if needed
#[build.environment]
#  NODE_VERSION = "18"

# === Redirects and Headers ===

# Root configuration to ensure index.html is served at the root
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Decks project redirects - removing unnecessary redirects since _site/decks is properly structured
[[redirects]]
  from = "/decks"
  to = "/decks/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/decks/*"
  to = "/decks/:splat"
  status = 200
  force = false

# BrahDB assets and data files
[[redirects]]
  from = "/brahdb/logos/*"
  to = "/brahdb/logos/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/brahdb/reviews/*"
  to = "/brahdb/reviews/:splat"
  status = 200
  force = true

# BrahDB SPA configuration
[[redirects]]
  from = "/brahdb"
  to = "/brahdb/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/brahdb/*"
  to = "/brahdb/index.html"
  status = 200
  force = true
  conditions = {Path = {Not = ["/brahdb/logos/*", "/brahdb/reviews/*"]}}

# Static project access
[[redirects]]
  from = "/bexarvoting/*"
  to = "/bexarvoting/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/friendfinder/*"
  to = "/friendfinder/:splat"
  status = 200
  force = false

# Assets handling
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# General 404 handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Consider adding a simple 404 rule if needed
# [[redirects]]
#  from = "/*"
#  to = "/404.html" # Assuming 404.html exists in the final _site
#  status = 404
