[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = "/decks/*"
  to = "/_site/decks/:splat"
  status = 200

[[redirects]]
  from = "/decks"
  to = "/_site/decks/index.html"
  status = 200