[[redirects]]
  from = "/decks/*"
  to = "/decks/_site/decks/:splat"
  status = 200

[[redirects]]
  from = "/decks"
  to = "/decks/_site/decks/index.html"
  status = 200

[[redirects]]
  from = "/decks/_site/*"
  to = "/decks/_site/decks/:splat"
  status = 200
