import type { Restaurant } from '../types/Review';

export const restaurantDisplay: Record<Restaurant, { display: string, logo: string }> = {
  'Arbys': { display: "Arby's", logo: 'arbys' },
  'AW': { display: 'A&W', logo: 'aw' },
  'BurgerKing': { display: 'Burger King', logo: 'burgerking' },
  'ChickFilA': { display: 'Chick-fil-A', logo: 'chickfila' },
  'Chipotle': { display: 'Chipotle', logo: 'chipotle' },
  'Culvers': { display: "Culver's", logo: 'culvers' },
  'DairyQueen': { display: 'Dairy Queen', logo: 'dairyqueen' },
  'DelTaco': { display: 'Del Taco', logo: 'deltaco' },
  'DiGiorno': { display: 'DiGiorno', logo: 'digiorno' },
  'Dominos': { display: "Domino's", logo: 'dominos' },
  'Dunkin': { display: 'Dunkin', logo: 'dunkin' },
  'FiveGuys': { display: 'Five Guys', logo: 'fiveguys' },
  'Freschetta': { display: 'Freschetta', logo: 'freschetta' },
  'Hardees': { display: "Hardee's", logo: 'hardees' },
  'HebrewNational': { display: 'Hebrew National', logo: 'hebrewnational' },
  'JackInTheBox': { display: 'Jack In The Box', logo: 'jackinthebox' },
  'JellO': { display: 'Jell-O', logo: 'jello' },
  'JimmyJohns': { display: "Jimmy John's", logo: 'jimmyjohns' },
  'KFC': { display: 'KFC', logo: 'kfc' },
  'KrispyKreme': { display: 'Krispy Kreme', logo: 'krispykreme' },
  'LittleCaesars': { display: "Little Caesar's", logo: 'littlecaesars' },
  'McDonalds': { display: "McDonald's", logo: 'mcdonalds' },
  'MrBeastBurger': { display: 'Mr. Beast Burger', logo: 'mrbeast' },
  'PandaExpress': { display: 'Panda Express', logo: 'pandaexpress' },
  'PaneraBread': { display: 'Panera Bread', logo: 'panerabread' },
  'PapaJohns': { display: "Papa John's", logo: 'papajohns' },
  'PDQ': { display: 'PDQ', logo: 'pdq' },
  'PizzaHut': { display: 'Pizza Hut', logo: 'pizzahut' },
  'Popeyes': { display: "Popeyes", logo: 'popeyes' },
  'RedBaron': { display: 'Red Baron Pizza', logo: 'redbaron' },
  'Sonic': { display: 'Sonic', logo: 'sonic' },
  'Starbucks': { display: 'Starbucks', logo: 'starbucks' },
  'SteakNShake': { display: "Steak 'n Shake", logo: 'steaknshake' },
  'Subway': { display: 'Subway', logo: 'subway' },
  'TacoBell': { display: 'Taco Bell', logo: 'tacobell' },
  'Wendys': { display: "Wendy's", logo: 'wendys' },
  'Wingstop': { display: 'Wingstop', logo: 'wingstop' },
  'Applebees': { display: "Applebee's", logo: 'applebees' },
  'BuffaloWildWings': { display: 'Buffalo Wild Wings', logo: 'buffalowildwings' },
  'CaliPizzaKitchen': { display: 'California Pizza Kitchen', logo: 'cpk' },
  'Coke': { display: 'Coca-Cola', logo: 'coke' },
  'Dennys': { display: "Denny's", logo: 'dennys' },
  'ShakeShack': { display: 'Shake Shack', logo: 'shakeshack' },
  'Zaxbys': { display: "Zaxby's", logo: 'zaxbys' },
  'Other': { display: 'Other', logo: 'other' },
  'Gerber': { display: 'Gerber', logo: 'gerber' },
  'Disney': { display: 'Walt Disney World', logo: 'disney' },
  'CheckersRallys': { display: "Checkers / Rally's", logo: 'checkers' },
  'Publix': { display: 'Publix', logo: 'publix' },
  'Sbarro': { display: 'Sbarro', logo: 'sbarro' },
  'HungryHowies': { display: "Hungry Howie's", logo: 'hungryhowies' },
  'WhiteCastle': { display: 'White Castle', logo: 'whitecastle' },
  'Oreo': { display: 'Oreo', logo: 'oreo' },
  'MunchPak': { display: 'MunchPak', logo: 'munchpak' },
  'CookOut': { display: 'Cook-Out', logo: 'cookout' },
  'Bojangles': { display: 'Bojangles', logo: 'bojangles' },
  'InNOut': { display: "In N' Out", logo: 'innout' },
  'ChipsAhoy': { display: 'Chips Ahoy', logo: 'chipsahoy' },
  'M&Ms': { display: "M&M's", logo: 'mms' },
  'Nathans': { display: "Nathan's Famous", logo: 'nathans' },
  'LongJohnSilvers': { display: "Long John Silver's", logo: 'longjohn' },
  'BostonMarket': { display: 'Boston Market', logo: 'bostonmarket' },
  'Pepsi': { display: 'Pepsi', logo: 'pepsi' },
  'MtnDew': { display: 'Mountain Dew', logo: 'mtndew' },
  'Soylent': { display: 'Soylent', logo: 'soylent' },
  'Hooters': { display: 'Hooters', logo: 'hooters' },
  'Krystal': { display: 'Krystal', logo: 'krystal' },
  'Biscuitville': { display: 'Biscuitville', logo: 'biscuitville' },
};